version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - "5432:5432"